# Meta Data for SEO

## Homepage
title = "Haaukins"
titleSeparator = "-"
titleAddition = "Haaukins Documentation"
description = "A Highly Accessible and Automated Virtualization Platform for Security Education"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/aau-network-security/haaukins-docs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Haaukins - Open Source Cyber Training Platform"

# Alert
alert = true
alertText = "Like Haaukins? <a style=\"color:#ff0101\"; class=\"alert-link\" href=\"https://github.com/aau-network-security/haaukins\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/aau-network-security/haaukins-docs"
editPage = true
